export const portfolioData = [
  {
    id: 4,
    img: "/assets/png/circle1.png",
    title: "Circle App",
    desc: "Circle App is a modern social platform with a sleek dark UI for interactive connections. It offers smooth interactions and personalized suggestions.",
    url: "https://circle-app-socialmedia.vercel.app",
        active: false,
    techs: [
      "/assets/svg/React.svg",
      "/assets/png/chakra.png",
      "/assets/svg/express-light.svg",
      "/assets/png/prisma.png",
      "/assets/png/ts.png",
      "/assets/svg/postgre.svg",
    ],
  },
  // {
  //   id: 3,
  //   img: "/assets/png/Meetio.png",
  //   title: "Meetio",
  //   desc: "Book your appointments in seconds. Fast, easy, and reliable.",
  //   url: "https://meetio-yi7k.vercel.app/",
  //       active: false,
  //   techs: [
  //     "/assets/svg/next-light.svg",
  //     "/assets/png/shadcn-light.png",
  //     "/assets/png/prisma.png",
  //     "/assets/png/tailwind.png",
  //     "/assets/png/javascript.png",
  //     "/assets/svg/pwa.svg",
  //   ],
  // },
  {
    id: 2,
    img: "/assets/png/travelhunt1.png",
    title: "TravelHunt",
    desc: "TravelHunt is a web app that helps users easily choose the best travel destination in Indonesia through informative visuals and descriptions.",
    url: "https://travel-hunt-alpha.vercel.app/",
        active: false,
    techs: [
      "/assets/svg/React.svg",
      "/assets/svg/express-light.svg",
      "/assets/png/prisma.png",
      "/assets/png/ts.png",
      "/assets/svg/postgre.svg",
    ],
  },
  // {
  //   id: 1,
  //   img: "/assets/png/writeon1.png",
  //   title: "WriteOn",
  //   desc: "Write On is a simple web app for creating and managing short stories. Built with Laravel and Breeze, it offers a clean UI and essential CRUD features in a lightweight project.",
  //   url: "https://write-onn.vercel.app/",
  //       active: false,
  //   techs: ["/assets/png/Laravel.png", "/assets/png/tailwind.png", "/assets/png/mysql.png"],
  // },
  // {
  //   id: 5,
  //   img: "/assets/png/lakoe1.png",
  //   title: "Lakoe",
  //   desc: "Lakoe App is a modern e-commerce platform with a minimalist UI for easy and secure shopping. It features personalized recommendations and a smooth checkout.",
  //   url: "https://www.lakoe.site/",
  //       active: false,
  //   techs: [
  //     "/assets/svg/React.svg",
  //     "/assets/png/chakra.png",
  //     "/assets/svg/express-light.svg",
  //     "/assets/png/prisma.png",
  //     "/assets/png/ts.png",
  //     "/assets/svg/postgre.svg",
  //   ],
  // },
  // {
  //   id: 6,
  //   img: "/assets/png/goodbudget.png",
  //   title: "GoodBudget",
  //   desc: "Easily log your daily expenses and income with just a few clicks. Get clear insights into your spending and manage your money better",
  //   url: "https://expo.dev/accounts/aryaaarz/projects/mobile/builds/505995d7-e29f-4c1d-aa87-aea539135490",
  //       active: true,
  //   techs: [
  //     "/assets/png/react-native.png",
  //     "/assets/svg/express-light.svg",
  //     "/assets/png/javascript.png",
  //     "/assets/svg/postgre.svg",
  //     "/assets/svg/expo-go.svg",
  //   ],
  // },
];
